In [1]:
print("Hello")

Hello


In [2]:
import time

a=list(range(1000))
b=list(range(1000))

start_point = time.time()
c = (x+y for x,y in zip(a,b))
end_point = time.time()
time_taken = end_point-start_point
print("Python Time", time_taken)

Python Time 8.988380432128906e-05


In [6]:
import numpy

a_numpy=list(range(1000))
b_numpy=list(range(1000))

start_time_numpy = time.time()
c= (x+y for x,y in zip(a_numpy,b_numpy))
end_time_numpy = time.time()
time_taken_numpy = end_time_numpy-start_time_numpy
print("time taken by numpy:", start_time_numpy)

time taken by numpy: 1771964851.5847096


In [30]:
import numpy as ny
arr1 =  ny.array([[1,2,3],[345,4,6,]])
print("arr1",arr1[1][0])
type(arr1[0])

arr1 345


numpy.ndarray

In [32]:
import numpy as np
np.arange(1,290,6)

array([  1,   7,  13,  19,  25,  31,  37,  43,  49,  55,  61,  67,  73,
        79,  85,  91,  97, 103, 109, 115, 121, 127, 133, 139, 145, 151,
       157, 163, 169, 175, 181, 187, 193, 199, 205, 211, 217, 223, 229,
       235, 241, 247, 253, 259, 265, 271, 277, 283, 289])

In [33]:
import numpy as np
np.linspace(5,100,5)

array([  5.  ,  28.75,  52.5 ,  76.25, 100.  ])

In [46]:
import numpy as np
np.zeros((3,3))
np.ones((3,3))
np.full((2,3), 4)
np.empty((2,2))
np.eye(5,6,2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])