In [ ]:
import numpy as ny


[1 2 3 4 5 6 7 8]


In [5]:
sys = ny.array(range(1,9))
print(sys)

[1 2 3 4 5 6 7 8]


In [7]:
ny.full((5,5),5)    

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [9]:
ny.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
ny.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
ny.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [13]:
ny.linspace(2,200,10)

array([  2.,  24.,  46.,  68.,  90., 112., 134., 156., 178., 200.])

In [15]:
ny.random.rand(1,2)

array([[0.5965536, 0.2151946]])