In [13]:
import numpy as n

In [ ]:


number_set = n.array([10,20,30,40,50,60,70])
print("Value of number set", number_set)

#size of array
print("Last number in array", number_set.size)

#last element of array
print("greatest number", number_set[-1])

#first element in array
print("First element", number_set[0])

#first 3 element
print("first 3 element",number_set[:3])

#last 3 element
print("Last 3 element", number_set[-3:])

print("value greater then 30",number_set[number_set>30])


print("shape of array",number_set.shape)


Value of number set [10 20 30 40 50 60 70]
Last number in array 7
greatest number 70
First element 10
first 3 element [10 20 30]
Last 3 element [50 60 70]
value greater then 30 [40 50 60 70]
shape of array (7,)


In [20]:
number_array=n.arange(1,21)  
number_array[number_array%3==0]     

array([ 3,  6,  9, 12, 15, 18])

In [41]:
two_d_array = n.random.randint(3,7,(5,5))
print("dd",two_d_array)
print("Third column", two_d_array[:,2])
print("second row",two_d_array[1,:])

dd [[5 3 4 3 4]
 [5 4 6 6 5]
 [6 4 6 3 6]
 [3 6 4 6 6]
 [3 3 6 6 5]]
Third column [4 6 6 4 6]
second row [5 4 6 6 5]


In [ ]:
a = n.arange(1, 7)


array([1, 2, 3, 4, 5, 6])

In [58]:
arr1 =n.random.randint(1,4,(5,6))
arr1.reshape(2,-1)

#adding 10 to all row
arr1+10

#adding 10 to particular row
print("addition to paritcular now",arr1[1]+10)
print("multiplicaiton to parituclar row",arr1[1]*2)
print("Mean of array",arr1.mean())

addition to paritcular now [11 11 13 11 13 12]
multiplicaiton to parituclar row [2 2 6 2 6 4]
Mean of array 1.9333333333333333
